export type Region = "US" | "UK" | "EA";
export type Category = "inflation" | "growth" | "jobs";
export type Importance = "critical" | "high" | "medium" | "supporting";
export type Transform =
  | "level"
  | "pct_change"
  | "pct_change_yoy"
  | "pct_change_mom"
  | "index"
  | "diff";
export type Source = "fred" | "eurostat" | "ons";

export interface MetricDef {
  id: string;
  region: Region;
  category: Category;
  subcategory: string;
  name: string;
  shortName: string;
  description: string;
  source: Source;
  seriesId: string;
  transform: Transform;
  frequency: "daily" | "weekly" | "monthly" | "quarterly";
  unit: string;
  importance: Importance;
  officialUrl: string;
  docsUrl: string;
  releaseName: string;
}

const BLS = "https://www.bls.gov";
const BEA = "https://www.bea.gov";
const FED = "https://www.federalreserve.gov";
const ATL = "https://www.atlantafed.org";
const ONS = "https://www.ons.gov.uk";
const BOE = "https://www.bankofengland.co.uk";
const EUROSTAT = "https://ec.europa.eu/eurostat";
const FRED = "https://fred.stlouisfed.org/series";

function fred(series: string) {
  return `${FRED}/${series}`;
}

export const METRICS: MetricDef[] = [
  // ─── US INFLATION ───────────────────────────────────────────
  {
    id: "us-cpi",
    region: "US",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "Consumer Price Index (All Urban, SA)",
    shortName: "CPI",
    description: "Headline US CPI level (index 1982-84=100).",
    source: "fred",
    seriesId: "CPIAUCSL",
    transform: "level",
    frequency: "monthly",
    unit: "index",
    importance: "critical",
    officialUrl: `${BLS}/cpi`,
    docsUrl: `${BLS}/news.release/cpi.toc.htm`,
    releaseName: "Consumer Price Index",
  },
  {
    id: "us-cpi-yoy",
    region: "US",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "CPI Year-over-Year",
    shortName: "CPI YoY",
    description: "Headline CPI percent change from year ago.",
    source: "fred",
    seriesId: "CPIAUCSL",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${BLS}/cpi`,
    docsUrl: `${BLS}/news.release/cpi.nr0.htm`,
    releaseName: "Consumer Price Index",
  },
  {
    id: "us-cpi-mom",
    region: "US",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "CPI Month-over-Month",
    shortName: "CPI MoM",
    description: "Headline CPI percent change from prior month.",
    source: "fred",
    seriesId: "CPIAUCSL",
    transform: "pct_change_mom",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${BLS}/cpi`,
    docsUrl: `${BLS}/news.release/cpi.nr0.htm`,
    releaseName: "Consumer Price Index",
  },
  {
    id: "us-core-cpi",
    region: "US",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "Core CPI (ex Food & Energy)",
    shortName: "Core CPI",
    description: "CPI less food and energy, SA.",
    source: "fred",
    seriesId: "CPILFESL",
    transform: "level",
    frequency: "monthly",
    unit: "index",
    importance: "critical",
    officialUrl: `${BLS}/cpi`,
    docsUrl: `${BLS}/news.release/cpi.nr0.htm`,
    releaseName: "Consumer Price Index",
  },
  {
    id: "us-core-cpi-yoy",
    region: "US",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "Core CPI Year-over-Year",
    shortName: "Core CPI YoY",
    description: "Core CPI percent change from year ago.",
    source: "fred",
    seriesId: "CPILFESL",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${BLS}/cpi`,
    docsUrl: `${BLS}/news.release/cpi.nr0.htm`,
    releaseName: "Consumer Price Index",
  },
  {
    id: "us-core-cpi-mom",
    region: "US",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "Core CPI Month-over-Month",
    shortName: "Core CPI MoM",
    description: "Core CPI percent change from prior month.",
    source: "fred",
    seriesId: "CPILFESL",
    transform: "pct_change_mom",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${BLS}/cpi`,
    docsUrl: `${BLS}/news.release/cpi.nr0.htm`,
    releaseName: "Consumer Price Index",
  },
  {
    id: "us-services-cpi-yoy",
    region: "US",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "US Services CPI YoY",
    shortName: "US Svc CPI",
    description: "CPI services less energy services YoY — Fed-watched services inflation (CUSR0000SASLE).",
    source: "fred",
    seriesId: "CUSR0000SASLE",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${BLS}/cpi`,
    docsUrl: `${BLS}/news.release/cpi.nr0.htm`,
    releaseName: "Consumer Price Index",
  },
  {
    id: "us-services-cpi-mom",
    region: "US",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "US Services CPI MoM",
    shortName: "US Svc MoM",
    description: "CPI services less energy services month-over-month (CUSR0000SASLE).",
    source: "fred",
    seriesId: "CUSR0000SASLE",
    transform: "pct_change_mom",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${BLS}/cpi`,
    docsUrl: `${BLS}/news.release/cpi.nr0.htm`,
    releaseName: "Consumer Price Index",
  },
  {
    id: "us-shelter-cpi-yoy",
    region: "US",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "US Shelter CPI YoY",
    shortName: "US Shelter",
    description: "CPI shelter YoY — largest services weight (CUSR0000SAH1).",
    source: "fred",
    seriesId: "CUSR0000SAH1",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${BLS}/cpi`,
    docsUrl: `${BLS}/news.release/cpi.nr0.htm`,
    releaseName: "Consumer Price Index",
  },
  {
    id: "us-shelter-cpi-mom",
    region: "US",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "US Shelter CPI MoM",
    shortName: "Shelter MoM",
    description: "CPI shelter month-over-month (CUSR0000SAH1).",
    source: "fred",
    seriesId: "CUSR0000SAH1",
    transform: "pct_change_mom",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${BLS}/cpi`,
    docsUrl: `${BLS}/news.release/cpi.nr0.htm`,
    releaseName: "Consumer Price Index",
  },
  {
    id: "us-core-goods-cpi-yoy",
    region: "US",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "US Core Goods CPI YoY",
    shortName: "Core Goods",
    description: "CPI commodities less food and energy YoY (CUSR0000SACL1E).",
    source: "fred",
    seriesId: "CUSR0000SACL1E",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${BLS}/cpi`,
    docsUrl: `${BLS}/news.release/cpi.nr0.htm`,
    releaseName: "Consumer Price Index",
  },
  {
    id: "us-core-goods-cpi-mom",
    region: "US",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "US Core Goods CPI MoM",
    shortName: "Core Goods MoM",
    description: "CPI commodities less food and energy month-over-month (CUSR0000SACL1E).",
    source: "fred",
    seriesId: "CUSR0000SACL1E",
    transform: "pct_change_mom",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${BLS}/cpi`,
    docsUrl: `${BLS}/news.release/cpi.nr0.htm`,
    releaseName: "Consumer Price Index",
  },
  {
    id: "us-food-cpi-yoy",
    region: "US",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "US Food CPI YoY",
    shortName: "US Food CPI",
    description: "CPI food YoY (FRED CPIUFDSL / BLS CUSR0000SAF1).",
    source: "fred",
    seriesId: "CPIUFDSL",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${BLS}/cpi`,
    docsUrl: `${BLS}/news.release/cpi.nr0.htm`,
    releaseName: "Consumer Price Index",
  },
  {
    id: "us-energy-cpi-yoy",
    region: "US",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "US Energy CPI YoY",
    shortName: "US Energy CPI",
    description: "CPI energy YoY (FRED CPIENGSL / BLS CUSR0000SA0E).",
    source: "fred",
    seriesId: "CPIENGSL",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${BLS}/cpi`,
    docsUrl: `${BLS}/news.release/cpi.nr0.htm`,
    releaseName: "Consumer Price Index",
  },
  {
    id: "us-ppi-final-demand",
    region: "US",
    category: "inflation",
    subcategory: "producer_prices",
    name: "PPI Final Demand",
    shortName: "PPI",
    description: "Producer Price Index final demand.",
    source: "fred",
    seriesId: "PPIFIS",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${BLS}/ppi`,
    docsUrl: `${BLS}/news.release/ppi.nr0.htm`,
    releaseName: "Producer Price Index",
  },
  {
    id: "us-ppi-core",
    region: "US",
    category: "inflation",
    subcategory: "producer_prices",
    name: "Core PPI Final Demand",
    shortName: "Core PPI",
    description: "PPI final demand less foods, energy, and trade services.",
    source: "fred",
    seriesId: "PPIFES",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${BLS}/ppi`,
    docsUrl: `${BLS}/news.release/ppi.nr0.htm`,
    releaseName: "Producer Price Index",
  },
  {
    id: "us-pce",
    region: "US",
    category: "inflation",
    subcategory: "pce",
    name: "PCE Price Index YoY",
    shortName: "PCE YoY",
    description: "Fed's preferred headline inflation gauge.",
    source: "fred",
    seriesId: "PCEPI",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${BEA}/data/personal-consumption-expenditures-price-index`,
    docsUrl: `${BEA}/news/personal-income`,
    releaseName: "Personal Income and Outlays",
  },
  {
    id: "us-core-pce",
    region: "US",
    category: "inflation",
    subcategory: "pce",
    name: "Core PCE Price Index YoY",
    shortName: "Core PCE YoY",
    description: "PCE excluding food and energy — Fed target metric.",
    source: "fred",
    seriesId: "PCEPILFE",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${BEA}/data/personal-consumption-expenditures-price-index`,
    docsUrl: `${BEA}/news/personal-income`,
    releaseName: "Personal Income and Outlays",
  },
  {
    id: "us-core-pce-mom",
    region: "US",
    category: "inflation",
    subcategory: "pce",
    name: "Core PCE Month-over-Month",
    shortName: "Core PCE MoM",
    description: "Monthly core PCE price change.",
    source: "fred",
    seriesId: "PCEPILFE",
    transform: "pct_change_mom",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${BEA}/data/personal-consumption-expenditures-price-index`,
    docsUrl: `${BEA}/news/personal-income`,
    releaseName: "Personal Income and Outlays",
  },
  {
    id: "us-cleveland-median-cpi",
    region: "US",
    category: "inflation",
    subcategory: "trimmed_measures",
    name: "Cleveland Fed Median CPI YoY",
    shortName: "Median CPI",
    description: "Median CPI — less noisy underlying inflation measure.",
    source: "fred",
    seriesId: "MEDCPIM158SFRBCLE",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: "https://www.clevelandfed.org/indicators-and-data/median-cpi",
    docsUrl: "https://www.clevelandfed.org/indicators-and-data/median-cpi",
    releaseName: "Median CPI",
  },
  {
    id: "us-cleveland-trimmed-cpi",
    region: "US",
    category: "inflation",
    subcategory: "trimmed_measures",
    name: "Cleveland Fed 16% Trimmed-Mean CPI",
    shortName: "Trimmed CPI",
    description: "16% trimmed-mean CPI from Cleveland Fed.",
    source: "fred",
    seriesId: "TRMMEANCPIM158SFRBCLE",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: "https://www.clevelandfed.org/indicators-and-data/median-cpi",
    docsUrl: "https://www.clevelandfed.org/indicators-and-data/median-cpi",
    releaseName: "Trimmed-Mean CPI",
  },
  {
    id: "us-sticky-cpi",
    region: "US",
    category: "inflation",
    subcategory: "trimmed_measures",
    name: "Atlanta Fed Sticky CPI YoY",
    shortName: "Sticky CPI",
    description: "Sticky-price CPI — slowly changing prices.",
    source: "fred",
    seriesId: "STICKCPIM159SFRBATL",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ATL}/research-and-data/data/sticky-price-cpi`,
    docsUrl: `${ATL}/research-and-data/data/sticky-price-cpi`,
    releaseName: "Sticky-Price CPI",
  },
  {
    id: "us-core-sticky-cpi",
    region: "US",
    category: "inflation",
    subcategory: "trimmed_measures",
    name: "Atlanta Fed Core Sticky CPI YoY",
    shortName: "Core Sticky CPI",
    description: "Sticky-price CPI excluding food and energy.",
    source: "fred",
    seriesId: "CORESTICKM159SFRBATL",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ATL}/research-and-data/data/sticky-price-cpi`,
    docsUrl: `${ATL}/research-and-data/data/sticky-price-cpi`,
    releaseName: "Sticky-Price CPI",
  },
  {
    id: "us-flexible-cpi",
    region: "US",
    category: "inflation",
    subcategory: "trimmed_measures",
    name: "Atlanta Fed Flexible CPI YoY",
    shortName: "Flexible CPI",
    description: "Flexible-price CPI — frequently changing prices.",
    source: "fred",
    seriesId: "FLEXCPIM159SFRBATL",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "medium",
    officialUrl: `${ATL}/chcs/stickyprice`,
    docsUrl: `${ATL}/chcs/stickyprice`,
    releaseName: "Flexible-Price CPI",
  },
  {
    id: "us-umich-inflation-exp-1y",
    region: "US",
    category: "inflation",
    subcategory: "expectations_consumer",
    name: "UMich Expected Inflation (1-Year)",
    shortName: "UMich 1Y Exp",
    description: "University of Michigan consumer inflation expectations, 1-year ahead.",
    source: "fred",
    seriesId: "MICH",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: "https://data.sca.isr.umich.edu/",
    docsUrl: "https://data.sca.isr.umich.edu/",
    releaseName: "Michigan Survey of Consumers",
  },
  {
    id: "us-cleveland-exp-inf-1y",
    region: "US",
    category: "inflation",
    subcategory: "expectations_consumer",
    name: "Cleveland Fed Expected Inflation (1-Year)",
    shortName: "Cleve 1Y Exp",
    description: "Cleveland Fed model-based expected inflation, 1-year.",
    source: "fred",
    seriesId: "EXPINF1YR",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: "https://www.clevelandfed.org/indicators-and-data/inflation-expectations",
    docsUrl: "https://www.clevelandfed.org/indicators-and-data/inflation-expectations",
    releaseName: "Inflation Expectations",
  },
  {
    id: "us-cleveland-exp-inf-2y",
    region: "US",
    category: "inflation",
    subcategory: "expectations_consumer",
    name: "Cleveland Fed Expected Inflation (2-Year)",
    shortName: "Cleve 2Y Exp",
    description: "Cleveland Fed model-based expected inflation, 2-year.",
    source: "fred",
    seriesId: "EXPINF2YR",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: "https://www.clevelandfed.org/indicators-and-data/inflation-expectations",
    docsUrl: "https://www.clevelandfed.org/indicators-and-data/inflation-expectations",
    releaseName: "Inflation Expectations",
  },
  {
    id: "us-cleveland-exp-inf-5y",
    region: "US",
    category: "inflation",
    subcategory: "expectations_consumer",
    name: "Cleveland Fed Expected Inflation (5-Year)",
    shortName: "Cleve 5Y Exp",
    description: "Cleveland Fed model-based expected inflation, 5-year.",
    source: "fred",
    seriesId: "EXPINF5YR",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: "https://www.clevelandfed.org/indicators-and-data/inflation-expectations",
    docsUrl: "https://www.clevelandfed.org/indicators-and-data/inflation-expectations",
    releaseName: "Inflation Expectations",
  },
  {
    id: "us-umich-sentiment",
    region: "US",
    category: "growth",
    subcategory: "sentiment",
    name: "University of Michigan Consumer Sentiment",
    shortName: "UMich Sentiment",
    description: "Michigan Survey of Consumers sentiment index (companion to inflation expectations).",
    source: "fred",
    seriesId: "UMCSENT",
    transform: "level",
    frequency: "monthly",
    unit: "index",
    importance: "high",
    officialUrl: "https://data.sca.isr.umich.edu/",
    docsUrl: "https://data.sca.isr.umich.edu/",
    releaseName: "Michigan Survey of Consumers",
  },
  {
    id: "us-breakeven-5y",
    region: "US",
    category: "inflation",
    subcategory: "expectations_market",
    name: "5-Year Breakeven Inflation Rate",
    shortName: "5Y BE",
    description: "Market-based inflation compensation from TIPS.",
    source: "fred",
    seriesId: "T5YIE",
    transform: "level",
    frequency: "daily",
    unit: "percent",
    importance: "high",
    officialUrl: FED,
    docsUrl: fred("T5YIE"),
    releaseName: "TIPS Breakevens",
  },
  {
    id: "us-breakeven-10y",
    region: "US",
    category: "inflation",
    subcategory: "expectations_market",
    name: "10-Year Breakeven Inflation Rate",
    shortName: "10Y BE",
    description: "10-year market-based inflation compensation.",
    source: "fred",
    seriesId: "T10YIE",
    transform: "level",
    frequency: "daily",
    unit: "percent",
    importance: "high",
    officialUrl: FED,
    docsUrl: fred("T10YIE"),
    releaseName: "TIPS Breakevens",
  },
  {
    id: "us-5y5y-forward",
    region: "US",
    category: "inflation",
    subcategory: "expectations_market",
    name: "5Y5Y Forward Inflation Expectation",
    shortName: "5Y5Y Fwd",
    description: "Five-year forward five-year inflation expectation rate.",
    source: "fred",
    seriesId: "T5YIFR",
    transform: "level",
    frequency: "daily",
    unit: "percent",
    importance: "high",
    officialUrl: FED,
    docsUrl: fred("T5YIFR"),
    releaseName: "Forward Inflation",
  },
  {
    id: "us-import-prices",
    region: "US",
    category: "inflation",
    subcategory: "producer_prices",
    name: "Import Price Index",
    shortName: "Import Prices",
    description: "Import price index — pipeline inflation from abroad.",
    source: "fred",
    seriesId: "IR",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${BLS}/mxp`,
    docsUrl: `${BLS}/news.release/ximpim.nr0.htm`,
    releaseName: "U.S. Import and Export Price Indexes",
  },
  {
    id: "us-manufacturers-new-orders",
    region: "US",
    category: "growth",
    subcategory: "demand",
    name: "Manufacturers New Orders MoM",
    shortName: "New Orders",
    description: "Manufacturers' new orders for all manufacturing industries.",
    source: "fred",
    seriesId: "NEWORDER",
    transform: "pct_change_mom",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: "https://www.census.gov/manufacturing/m3/index.html",
    docsUrl: "https://www.census.gov/manufacturing/m3/index.html",
    releaseName: "Manufacturers' Shipments, Inventories, and Orders",
  },
  {
    id: "us-eci-wages",
    region: "US",
    category: "inflation",
    subcategory: "labor_costs",
    name: "Employment Cost Index — Wages & Salaries",
    shortName: "ECI Wages",
    description: "ECI wages and salaries for civilian workers, QoQ % change from index.",
    source: "fred",
    seriesId: "ECIWAG",
    transform: "pct_change",
    frequency: "quarterly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${BLS}/eci`,
    docsUrl: `${BLS}/news.release/eci.nr0.htm`,
    releaseName: "Employment Cost Index",
  },
  {
    id: "us-eci-total",
    region: "US",
    category: "inflation",
    subcategory: "labor_costs",
    name: "Employment Cost Index — Total Compensation",
    shortName: "ECI Total",
    description: "ECI total compensation civilian workers.",
    source: "fred",
    seriesId: "ECIALLCIV",
    transform: "level",
    frequency: "quarterly",
    unit: "index",
    importance: "critical",
    officialUrl: `${BLS}/eci`,
    docsUrl: `${BLS}/news.release/eci.nr0.htm`,
    releaseName: "Employment Cost Index",
  },
  {
    id: "us-ahe",
    region: "US",
    category: "inflation",
    subcategory: "labor_costs",
    name: "Average Hourly Earnings YoY",
    shortName: "AHE YoY",
    description: "Average hourly earnings of production and nonsupervisory employees.",
    source: "fred",
    seriesId: "CES0500000003",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${BLS}/ces`,
    docsUrl: `${BLS}/news.release/empsit.nr0.htm`,
    releaseName: "Employment Situation",
  },
  {
    id: "us-atlanta-wage",
    region: "US",
    category: "inflation",
    subcategory: "labor_costs",
    name: "Atlanta Fed Wage Growth Tracker",
    shortName: "Wage Tracker",
    description: "Median wage growth of continuously employed workers.",
    source: "fred",
    seriesId: "FRBATLWGT3MMAUMHWGO",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ATL}/chcs/wage-growth-tracker`,
    docsUrl: `${ATL}/chcs/wage-growth-tracker`,
    releaseName: "Wage Growth Tracker",
  },
  {
    id: "us-unit-labor-cost",
    region: "US",
    category: "inflation",
    subcategory: "labor_costs",
    name: "Nonfarm Unit Labor Costs YoY",
    shortName: "ULC YoY",
    description: "Unit labor costs in the nonfarm business sector.",
    source: "fred",
    seriesId: "ULCNFB",
    transform: "pct_change_yoy",
    frequency: "quarterly",
    unit: "percent",
    importance: "high",
    officialUrl: `${BLS}/lpc`,
    docsUrl: `${BLS}/news.release/prod2.nr0.htm`,
    releaseName: "Productivity and Costs",
  },

  // ─── US GROWTH ──────────────────────────────────────────────
  {
    id: "us-gdp-real",
    region: "US",
    category: "growth",
    subcategory: "gdp",
    name: "Real GDP (QoQ SAAR)",
    shortName: "Real GDP",
    description: "Real gross domestic product, percent change from preceding period SAAR.",
    source: "fred",
    seriesId: "A191RL1Q225SBEA",
    transform: "level",
    frequency: "quarterly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${BEA}/data/gdp`,
    docsUrl: `${BEA}/news/gross-domestic-product`,
    releaseName: "Gross Domestic Product",
  },
  {
    id: "us-gdp-now",
    region: "US",
    category: "growth",
    subcategory: "gdp",
    name: "Atlanta Fed GDPNow",
    shortName: "GDPNow",
    description: "Real-time GDP growth nowcast.",
    source: "fred",
    seriesId: "GDPNOW",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${ATL}/cqer/research/gdpnow`,
    docsUrl: `${ATL}/cqer/research/gdpnow`,
    releaseName: "GDPNow",
  },
  {
    id: "us-industrial-production",
    region: "US",
    category: "growth",
    subcategory: "production",
    name: "Industrial Production YoY",
    shortName: "IP YoY",
    description: "Industrial production index year-over-year.",
    source: "fred",
    seriesId: "INDPRO",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${FED}/releases/g17/`,
    docsUrl: `${FED}/releases/g17/current/default.htm`,
    releaseName: "Industrial Production and Capacity Utilization",
  },
  {
    id: "us-capacity-utilization",
    region: "US",
    category: "growth",
    subcategory: "production",
    name: "Capacity Utilization",
    shortName: "Cap Util",
    description: "Total industry capacity utilization.",
    source: "fred",
    seriesId: "TCU",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "medium",
    officialUrl: `${FED}/releases/g17/`,
    docsUrl: `${FED}/releases/g17/current/default.htm`,
    releaseName: "Industrial Production and Capacity Utilization",
  },
  {
    id: "us-retail-sales",
    region: "US",
    category: "growth",
    subcategory: "demand",
    name: "Retail Sales MoM",
    shortName: "Retail Sales",
    description: "Advance retail and food services sales MoM.",
    source: "fred",
    seriesId: "RSAFS",
    transform: "pct_change_mom",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: "https://www.census.gov/retail/index.html",
    docsUrl: "https://www.census.gov/retail/marts/www/marts_current.pdf",
    releaseName: "Advance Monthly Retail Trade",
  },
  {
    id: "us-retail-sales-ex-auto",
    region: "US",
    category: "growth",
    subcategory: "demand",
    name: "Retail Sales ex Auto MoM",
    shortName: "Retail ex Auto",
    description: "Retail sales excluding motor vehicles.",
    source: "fred",
    seriesId: "RSFSXMV",
    transform: "pct_change_mom",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: "https://www.census.gov/retail/index.html",
    docsUrl: "https://www.census.gov/retail/marts/www/marts_current.pdf",
    releaseName: "Advance Monthly Retail Trade",
  },
  {
    id: "us-durable-goods",
    region: "US",
    category: "growth",
    subcategory: "demand",
    name: "Durable Goods Orders MoM",
    shortName: "Durables",
    description: "Manufacturers' new orders for durable goods.",
    source: "fred",
    seriesId: "DGORDER",
    transform: "pct_change_mom",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: "https://www.census.gov/manufacturing/m3/index.html",
    docsUrl: "https://www.census.gov/manufacturing/m3/adv/pdf/durgd.pdf",
    releaseName: "Advance Report on Durable Goods",
  },
  {
    id: "us-housing-starts",
    region: "US",
    category: "growth",
    subcategory: "housing",
    name: "Housing Starts",
    shortName: "Starts",
    description: "New privately owned housing units started (SAAR, thousands).",
    source: "fred",
    seriesId: "HOUST",
    transform: "level",
    frequency: "monthly",
    unit: "thousands",
    importance: "high",
    officialUrl: "https://www.census.gov/construction/nrc/index.html",
    docsUrl: "https://www.census.gov/construction/nrc/pdf/newresconst.pdf",
    releaseName: "New Residential Construction",
  },
  {
    id: "us-building-permits",
    region: "US",
    category: "growth",
    subcategory: "housing",
    name: "Building Permits",
    shortName: "Permits",
    description: "New private housing units authorized by building permits.",
    source: "fred",
    seriesId: "PERMIT",
    transform: "level",
    frequency: "monthly",
    unit: "thousands",
    importance: "high",
    officialUrl: "https://www.census.gov/construction/nrc/index.html",
    docsUrl: "https://www.census.gov/construction/nrc/pdf/newresconst.pdf",
    releaseName: "New Residential Construction",
  },
  {
    id: "us-empire-state",
    region: "US",
    category: "growth",
    subcategory: "pmi",
    name: "NY Fed Empire State Manufacturing Index",
    shortName: "Empire State",
    description: "Regional manufacturing survey — timely PMI-style activity signal (ISM series retired from public FRED).",
    source: "fred",
    seriesId: "GACDISA066MSFRBNY",
    transform: "level",
    frequency: "monthly",
    unit: "index",
    importance: "critical",
    officialUrl: "https://www.newyorkfed.org/survey/empire/empiresurvey_overview",
    docsUrl: "https://www.newyorkfed.org/survey/empire/empiresurvey_overview",
    releaseName: "Empire State Manufacturing Survey",
  },
  {
    id: "us-dallas-fed-activity",
    region: "US",
    category: "growth",
    subcategory: "pmi",
    name: "Dallas Fed Business Activity Index",
    shortName: "Dallas Activity",
    description: "Texas business activity diffusion index — regional PMI analogue.",
    source: "fred",
    seriesId: "BACTSAMFRBDAL",
    transform: "level",
    frequency: "monthly",
    unit: "index",
    importance: "high",
    officialUrl: "https://www.dallasfed.org/research/surveys/tssb",
    docsUrl: "https://www.dallasfed.org/research/surveys/tssb",
    releaseName: "Texas Business Outlook Surveys",
  },
  {
    id: "us-mfg-employment",
    region: "US",
    category: "jobs",
    subcategory: "payrolls",
    name: "Manufacturing Employment Level",
    shortName: "Mfg Payrolls",
    description: "All employees, manufacturing (thousands).",
    source: "fred",
    seriesId: "MANEMP",
    transform: "level",
    frequency: "monthly",
    unit: "thousands",
    importance: "high",
    officialUrl: `${BLS}/ces`,
    docsUrl: `${BLS}/news.release/empsit.nr0.htm`,
    releaseName: "Employment Situation",
  },
  {
    id: "us-cfnai",
    region: "US",
    category: "growth",
    subcategory: "activity",
    name: "Chicago Fed National Activity Index",
    shortName: "CFNAI",
    description: "Weighted average of 85 monthly US economic indicators.",
    source: "fred",
    seriesId: "CFNAI",
    transform: "level",
    frequency: "monthly",
    unit: "index",
    importance: "medium",
    officialUrl: "https://www.chicagofed.org/research/data/cfnai/current-data",
    docsUrl: "https://www.chicagofed.org/research/data/cfnai/current-data",
    releaseName: "CFNAI",
  },
  {
    id: "us-personal-spending",
    region: "US",
    category: "growth",
    subcategory: "demand",
    name: "Real Personal Consumption MoM",
    shortName: "Real PCE MoM",
    description: "Real personal consumption expenditures monthly change.",
    source: "fred",
    seriesId: "PCEC96",
    transform: "pct_change_mom",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${BEA}/data/personal-consumption-expenditures`,
    docsUrl: `${BEA}/news/personal-income`,
    releaseName: "Personal Income and Outlays",
  },

  // ─── US JOBS ────────────────────────────────────────────────
  {
    id: "us-nfp",
    region: "US",
    category: "jobs",
    subcategory: "payrolls",
    name: "Nonfarm Payrolls Change",
    shortName: "NFP",
    description: "All employees, total nonfarm, monthly change (thousands).",
    source: "fred",
    seriesId: "PAYEMS",
    transform: "diff",
    frequency: "monthly",
    unit: "thousands",
    importance: "critical",
    officialUrl: `${BLS}/ces`,
    docsUrl: `${BLS}/news.release/empsit.nr0.htm`,
    releaseName: "Employment Situation",
  },
  {
    id: "us-adp-change",
    region: "US",
    category: "jobs",
    subcategory: "payrolls",
    name: "ADP Nonfarm Private Employment Change",
    shortName: "ADP Change",
    description: "Monthly change in ADP National Employment Report private payrolls (thousands).",
    source: "fred",
    seriesId: "ADPMNUSNERSA",
    transform: "diff",
    frequency: "monthly",
    unit: "thousands",
    importance: "critical",
    officialUrl: "https://adpemploymentreport.com/",
    docsUrl: "https://adpemploymentreport.com/",
    releaseName: "ADP National Employment Report",
  },
  {
    id: "us-adp-level",
    region: "US",
    category: "jobs",
    subcategory: "payrolls",
    name: "ADP Nonfarm Private Employment Level",
    shortName: "ADP Level",
    description: "ADP National Employment Report — private nonfarm employment level (thousands).",
    source: "fred",
    seriesId: "ADPMNUSNERSA",
    transform: "level",
    frequency: "monthly",
    unit: "thousands",
    importance: "high",
    officialUrl: "https://adpemploymentreport.com/",
    docsUrl: "https://adpemploymentreport.com/",
    releaseName: "ADP National Employment Report",
  },
  {
    id: "us-payrolls-level",
    region: "US",
    category: "jobs",
    subcategory: "payrolls",
    name: "Total Nonfarm Payrolls Level",
    shortName: "Payrolls Level",
    description: "All employees, total nonfarm (thousands).",
    source: "fred",
    seriesId: "PAYEMS",
    transform: "level",
    frequency: "monthly",
    unit: "thousands",
    importance: "critical",
    officialUrl: `${BLS}/ces`,
    docsUrl: `${BLS}/news.release/empsit.nr0.htm`,
    releaseName: "Employment Situation",
  },
  {
    id: "us-unemployment",
    region: "US",
    category: "jobs",
    subcategory: "unemployment",
    name: "Unemployment Rate",
    shortName: "U-3",
    description: "Civilian unemployment rate.",
    source: "fred",
    seriesId: "UNRATE",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${BLS}/cps`,
    docsUrl: `${BLS}/news.release/empsit.nr0.htm`,
    releaseName: "Employment Situation",
  },
  {
    id: "us-u6",
    region: "US",
    category: "jobs",
    subcategory: "unemployment",
    name: "U-6 Underemployment Rate",
    shortName: "U-6",
    description: "Total unemployed plus marginally attached plus part-time for economic reasons.",
    source: "fred",
    seriesId: "U6RATE",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${BLS}/cps`,
    docsUrl: `${BLS}/news.release/empsit.nr0.htm`,
    releaseName: "Employment Situation",
  },
  {
    id: "us-participation",
    region: "US",
    category: "jobs",
    subcategory: "participation",
    name: "Labor Force Participation Rate",
    shortName: "LFPR",
    description: "Civilian labor force participation rate.",
    source: "fred",
    seriesId: "CIVPART",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${BLS}/cps`,
    docsUrl: `${BLS}/news.release/empsit.nr0.htm`,
    releaseName: "Employment Situation",
  },
  {
    id: "us-employment-population",
    region: "US",
    category: "jobs",
    subcategory: "participation",
    name: "Employment-Population Ratio",
    shortName: "EPOP",
    description: "Civilian employment-population ratio.",
    source: "fred",
    seriesId: "EMRATIO",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${BLS}/cps`,
    docsUrl: `${BLS}/news.release/empsit.nr0.htm`,
    releaseName: "Employment Situation",
  },
  {
    id: "us-jolts-openings",
    region: "US",
    category: "jobs",
    subcategory: "jolts",
    name: "JOLTS Job Openings",
    shortName: "Openings",
    description: "Total nonfarm job openings (thousands).",
    source: "fred",
    seriesId: "JTSJOL",
    transform: "level",
    frequency: "monthly",
    unit: "thousands",
    importance: "critical",
    officialUrl: `${BLS}/jlt`,
    docsUrl: `${BLS}/news.release/jolts.nr0.htm`,
    releaseName: "Job Openings and Labor Turnover",
  },
  {
    id: "us-jolts-quits",
    region: "US",
    category: "jobs",
    subcategory: "jolts",
    name: "JOLTS Quits Rate",
    shortName: "Quits Rate",
    description: "Quits rate — proxy for labor market confidence.",
    source: "fred",
    seriesId: "JTSQUR",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${BLS}/jlt`,
    docsUrl: `${BLS}/news.release/jolts.nr0.htm`,
    releaseName: "Job Openings and Labor Turnover",
  },
  {
    id: "us-jolts-hires",
    region: "US",
    category: "jobs",
    subcategory: "jolts",
    name: "JOLTS Hires Rate",
    shortName: "Hires Rate",
    description: "Hires rate from JOLTS.",
    source: "fred",
    seriesId: "JTSHIR",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "medium",
    officialUrl: `${BLS}/jlt`,
    docsUrl: `${BLS}/news.release/jolts.nr0.htm`,
    releaseName: "Job Openings and Labor Turnover",
  },
  {
    id: "us-jolts-layoffs",
    region: "US",
    category: "jobs",
    subcategory: "jolts",
    name: "JOLTS Layoffs & Discharges Rate",
    shortName: "Layoffs Rate",
    description: "Layoffs and discharges rate.",
    source: "fred",
    seriesId: "JTSLDR",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "medium",
    officialUrl: `${BLS}/jlt`,
    docsUrl: `${BLS}/news.release/jolts.nr0.htm`,
    releaseName: "Job Openings and Labor Turnover",
  },
  {
    id: "us-initial-claims",
    region: "US",
    category: "jobs",
    subcategory: "claims",
    name: "Initial Jobless Claims",
    shortName: "Initial Claims",
    description: "Weekly initial unemployment insurance claims (SA).",
    source: "fred",
    seriesId: "ICSA",
    transform: "level",
    frequency: "weekly",
    unit: "number",
    importance: "critical",
    officialUrl: "https://oui.doleta.gov/unemploy/claims.asp",
    docsUrl: "https://oui.doleta.gov/unemploy/claims_arch.asp",
    releaseName: "Unemployment Insurance Weekly Claims",
  },
  {
    id: "us-continuing-claims",
    region: "US",
    category: "jobs",
    subcategory: "claims",
    name: "Continuing Jobless Claims",
    shortName: "Continuing Claims",
    description: "Continued claims under state programs (SA).",
    source: "fred",
    seriesId: "CCSA",
    transform: "level",
    frequency: "weekly",
    unit: "number",
    importance: "high",
    officialUrl: "https://oui.doleta.gov/unemploy/claims.asp",
    docsUrl: "https://oui.doleta.gov/unemploy/claims_arch.asp",
    releaseName: "Unemployment Insurance Weekly Claims",
  },
  {
    id: "us-temp-help",
    region: "US",
    category: "jobs",
    subcategory: "leading",
    name: "Temporary Help Services Employment",
    shortName: "Temp Help",
    description: "Leading indicator of labor demand.",
    source: "fred",
    seriesId: "TEMPHELPS",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "medium",
    officialUrl: `${BLS}/ces`,
    docsUrl: `${BLS}/news.release/empsit.nr0.htm`,
    releaseName: "Employment Situation",
  },
  {
    id: "us-avg-workweek",
    region: "US",
    category: "jobs",
    subcategory: "hours",
    name: "Average Weekly Hours",
    shortName: "Workweek",
    description: "Average weekly hours of all employees.",
    source: "fred",
    seriesId: "AWHAETP",
    transform: "level",
    frequency: "monthly",
    unit: "hours",
    importance: "medium",
    officialUrl: `${BLS}/ces`,
    docsUrl: `${BLS}/news.release/empsit.nr0.htm`,
    releaseName: "Employment Situation",
  },

  // ─── UK INFLATION ───────────────────────────────────────────
  {
    id: "uk-cpi-yoy",
    region: "UK",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "UK CPI YoY",
    shortName: "UK CPI YoY",
    description: "UK Consumer Prices Index annual growth rate (ONS).",
    source: "ons",
    seriesId: "D7G7",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${ONS}/economy/inflationandpriceindices`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest`,
    releaseName: "Consumer Price Inflation",
  },
  {
    id: "uk-cpih-yoy",
    region: "UK",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "UK CPIH YoY",
    shortName: "CPIH YoY",
    description: "CPI including owner occupiers' housing costs.",
    source: "ons",
    seriesId: "L55O",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${ONS}/economy/inflationandpriceindices`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest`,
    releaseName: "Consumer Price Inflation",
  },
  {
    id: "uk-core-cpi-yoy",
    region: "UK",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "UK Core CPI YoY",
    shortName: "UK Core CPI",
    description: "UK CPI excluding energy, food, alcohol and tobacco (ONS DKO8 12-month %).",
    source: "ons",
    seriesId: "DKO8",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${ONS}/economy/inflationandpriceindices`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest`,
    releaseName: "Consumer Price Inflation",
  },
  {
    id: "uk-cpi-mom",
    region: "UK",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "UK CPI MoM",
    shortName: "UK CPI MoM",
    description: "UK CPI all-items monthly rate (ONS D7OE).",
    source: "ons",
    seriesId: "D7OE",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${ONS}/economy/inflationandpriceindices/timeseries/d7oe/mm23`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest`,
    releaseName: "Consumer Price Inflation",
  },
  {
    id: "uk-core-cpi-mom",
    region: "UK",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "UK Core CPI MoM",
    shortName: "UK Core MoM",
    description:
      "UK core CPI month-on-month % from ONS DKC6 index (no official core monthly-rate CDID).",
    source: "ons",
    seriesId: "DKC6",
    transform: "pct_change_mom",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ONS}/economy/inflationandpriceindices/timeseries/dkc6/mm23`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest`,
    releaseName: "Consumer Price Inflation",
  },
  {
    id: "uk-services-cpi-yoy",
    region: "UK",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "UK Services CPI YoY",
    shortName: "UK Svc CPI",
    description: "UK CPI services annual rate (ONS D7NN) — key BoE services inflation measure.",
    source: "ons",
    seriesId: "D7NN",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${ONS}/economy/inflationandpriceindices/timeseries/d7nn/mm23`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest`,
    releaseName: "Consumer Price Inflation",
  },
  {
    id: "uk-services-cpi-mom",
    region: "UK",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "UK Services CPI MoM",
    shortName: "UK Svc MoM",
    description: "UK CPI services monthly rate (ONS D7MV).",
    source: "ons",
    seriesId: "D7MV",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ONS}/economy/inflationandpriceindices/timeseries/d7mv/mm23`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest`,
    releaseName: "Consumer Price Inflation",
  },
  {
    id: "uk-goods-cpi-yoy",
    region: "UK",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "UK Goods CPI YoY",
    shortName: "UK Goods CPI",
    description: "UK CPI goods annual rate (ONS D7NM).",
    source: "ons",
    seriesId: "D7NM",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ONS}/economy/inflationandpriceindices/timeseries/d7nm/mm23`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest`,
    releaseName: "Consumer Price Inflation",
  },
  {
    id: "uk-goods-cpi-mom",
    region: "UK",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "UK Goods CPI MoM",
    shortName: "UK Goods MoM",
    description: "UK CPI goods monthly rate (ONS D7MU).",
    source: "ons",
    seriesId: "D7MU",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "medium",
    officialUrl: `${ONS}/economy/inflationandpriceindices/timeseries/d7mu/mm23`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest`,
    releaseName: "Consumer Price Inflation",
  },
  {
    id: "uk-food-cpi-yoy",
    region: "UK",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "UK Food CPI YoY",
    shortName: "UK Food CPI",
    description: "UK CPI food & non-alcoholic beverages annual rate (ONS D7G8).",
    source: "ons",
    seriesId: "D7G8",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ONS}/economy/inflationandpriceindices/timeseries/d7g8/mm23`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest`,
    releaseName: "Consumer Price Inflation",
  },
  {
    id: "uk-energy-cpi-yoy",
    region: "UK",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "UK Energy CPI YoY",
    shortName: "UK Energy CPI",
    description: "UK CPI electricity, gas and other fuels annual rate (ONS D7GT).",
    source: "ons",
    seriesId: "D7GT",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ONS}/economy/inflationandpriceindices/timeseries/d7gt/mm23`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest`,
    releaseName: "Consumer Price Inflation",
  },
  {
    id: "uk-housing-cpi-yoy",
    region: "UK",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "UK Housing CPI YoY",
    shortName: "UK Housing CPI",
    description: "UK CPI housing, water and fuels annual rate (ONS D7GB).",
    source: "ons",
    seriesId: "D7GB",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ONS}/economy/inflationandpriceindices/timeseries/d7gb/mm23`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest`,
    releaseName: "Consumer Price Inflation",
  },
  {
    id: "uk-rpi-yoy",
    region: "UK",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "UK RPI YoY",
    shortName: "RPI YoY",
    description: "Retail Prices Index annual rate (ONS).",
    source: "ons",
    seriesId: "CZBH",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "medium",
    officialUrl: `${ONS}/economy/inflationandpriceindices`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/consumerpriceinflation/latest`,
    releaseName: "Consumer Price Inflation",
  },
  {
    id: "uk-ppi-output-yoy",
    region: "UK",
    category: "inflation",
    subcategory: "producer_prices",
    name: "UK Output PPI YoY",
    shortName: "UK PPI Out",
    description: "Factory gate / output producer prices, year-over-year (ONS GB7S manufactured products).",
    source: "ons",
    seriesId: "GB7S",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ONS}/economy/inflationandpriceindices`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/producerpriceinflation/latest`,
    releaseName: "Producer Price Inflation",
  },
  {
    id: "uk-awe-regular-yoy",
    region: "UK",
    category: "inflation",
    subcategory: "labor_costs",
    name: "UK Average Weekly Earnings (Regular Pay) YoY",
    shortName: "AWE Regular",
    description: "Regular pay 3-month average YoY excluding bonuses (ONS KAI9) — key BoE wage measure.",
    source: "ons",
    seriesId: "KAI9",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${ONS}/employmentandlabourmarket/peopleinwork/earningsandworkinghours`,
    docsUrl: `${ONS}/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/bulletins/averageweeklyearningsingreatbritain/latest`,
    releaseName: "Average Weekly Earnings",
  },
  {
    id: "uk-ppi-input-yoy",
    region: "UK",
    category: "inflation",
    subcategory: "producer_prices",
    name: "UK Input PPI YoY",
    shortName: "UK PPI In",
    description: "Materials and fuels purchased by manufacturers, year-over-year (from ONS input index).",
    source: "ons",
    seriesId: "GHIP",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ONS}/economy/inflationandpriceindices`,
    docsUrl: `${ONS}/economy/inflationandpriceindices/bulletins/producerpriceinflation/latest`,
    releaseName: "Producer Price Inflation",
  },

  // ─── UK GROWTH ──────────────────────────────────────────────
  {
    id: "uk-gdp-yoy",
    region: "UK",
    category: "growth",
    subcategory: "gdp",
    name: "UK GDP YoY",
    shortName: "UK GDP YoY",
    description: "UK real GDP quarter-on-quarter-a-year-ago growth (ONS IHYR, CVM SA %).",
    source: "ons",
    seriesId: "IHYR",
    transform: "level",
    frequency: "quarterly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${ONS}/economy/grossdomesticproductgdp/timeseries/ihyr/pn2`,
    docsUrl: `${ONS}/economy/grossdomesticproductgdp/bulletins/gdpfirstquarterlyestimateuk/latest`,
    releaseName: "GDP First Quarterly Estimate",
  },
  {
    id: "uk-gdp-qoq",
    region: "UK",
    category: "growth",
    subcategory: "gdp",
    name: "UK Real GDP QoQ",
    shortName: "UK GDP QoQ",
    description: "UK real GDP quarter-on-quarter growth (ONS IHYQ, CVM SA %).",
    source: "ons",
    seriesId: "IHYQ",
    transform: "level",
    frequency: "quarterly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${ONS}/economy/grossdomesticproductgdp/timeseries/ihyq/pn2`,
    docsUrl: `${ONS}/economy/grossdomesticproductgdp/bulletins/gdpfirstquarterlyestimateuk/latest`,
    releaseName: "GDP First Quarterly Estimate",
  },
  {
    id: "uk-gdp-mom",
    region: "UK",
    category: "growth",
    subcategory: "gdp",
    name: "UK Monthly GDP MoM",
    shortName: "UK GDP MoM",
    description: "Monthly GDP (GVA) month-on-month growth (ONS ECYX, CVM SA %).",
    source: "ons",
    seriesId: "ECYX",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${ONS}/economy/grossdomesticproductgdp/timeseries/ecyx/mgdp`,
    docsUrl: `${ONS}/economy/grossdomesticproductgdp/bulletins/gdpmonthlyestimateuk/latest`,
    releaseName: "GDP Monthly Estimate",
  },
  {
    id: "uk-gdp-3m-yoy",
    region: "UK",
    category: "growth",
    subcategory: "gdp",
    name: "UK Monthly GDP 3m YoY",
    shortName: "UK GDP 3m YoY",
    description: "Monthly GDP 3-month on 3-month a year ago growth (ONS ED9T) — ONS bulletin-style YoY.",
    source: "ons",
    seriesId: "ED9T",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ONS}/economy/grossdomesticproductgdp/timeseries/ed9t/mgdp`,
    docsUrl: `${ONS}/economy/grossdomesticproductgdp/bulletins/gdpmonthlyestimateuk/latest`,
    releaseName: "GDP Monthly Estimate",
  },
  {
    id: "uk-industrial-production",
    region: "UK",
    category: "growth",
    subcategory: "production",
    name: "UK Industrial Production YoY",
    shortName: "UK IP",
    description: "UK index of production (ONS K222 B-E CVMSA), year-over-year.",
    source: "ons",
    seriesId: "K222",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ONS}/economy/economicoutputandproductivity`,
    docsUrl: `${ONS}/economy/economicoutputandproductivity/output/bulletins/indexofproduction/latest`,
    releaseName: "Index of Production",
  },
  {
    id: "uk-retail-sales",
    region: "UK",
    category: "growth",
    subcategory: "demand",
    name: "UK Retail Sales Volume YoY",
    shortName: "UK Retail",
    description: "Retail sales volumes annual growth (ONS J5EK).",
    source: "ons",
    seriesId: "J5EK",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ONS}/businessindustryandtrade/retailindustry`,
    docsUrl: `${ONS}/businessindustryandtrade/retailindustry/bulletins/retailsales/latest`,
    releaseName: "Retail Sales",
  },
  {
    id: "uk-cli",
    region: "UK",
    category: "growth",
    subcategory: "leading",
    name: "UK OECD Composite Leading Indicator",
    shortName: "UK CLI",
    description: "OECD composite leading indicator for the United Kingdom.",
    source: "fred",
    seriesId: "GBRLOLITOAASTSAM",
    transform: "level",
    frequency: "monthly",
    unit: "index",
    importance: "medium",
    officialUrl: "https://www.oecd.org/en/data/indicators/composite-leading-indicator-cli.html",
    docsUrl: "https://www.oecd.org/en/data/indicators/composite-leading-indicator-cli.html",
    releaseName: "OECD CLI",
  },
  {
    id: "uk-business-confidence",
    region: "UK",
    category: "growth",
    subcategory: "sentiment",
    name: "UK Business Confidence",
    shortName: "UK Biz Conf",
    description: "OECD business confidence indicator for the UK.",
    source: "fred",
    seriesId: "BSCICP02GBM460S",
    transform: "level",
    frequency: "monthly",
    unit: "index",
    importance: "high",
    officialUrl: BOE,
    docsUrl: `${ONS}/economy`,
    releaseName: "Business Confidence",
  },

  // ─── UK JOBS ────────────────────────────────────────────────
  {
    id: "uk-unemployment",
    region: "UK",
    category: "jobs",
    subcategory: "unemployment",
    name: "UK Unemployment Rate",
    shortName: "UK U-Rate",
    description: "ILO unemployment rate (aged 16+) — ONS MGSX.",
    source: "ons",
    seriesId: "MGSX",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${ONS}/employmentandlabourmarket/peoplenotinwork/unemployment`,
    docsUrl: `${ONS}/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/bulletins/uklabourmarket/latest`,
    releaseName: "Labour Market",
  },
  {
    id: "uk-employment-level",
    region: "UK",
    category: "jobs",
    subcategory: "employment",
    name: "UK Employment Level",
    shortName: "UK Emp Level",
    description: "Total employment aged 16+ (ONS MGRZ, thousands).",
    source: "ons",
    seriesId: "MGRZ",
    transform: "level",
    frequency: "monthly",
    unit: "thousands",
    importance: "high",
    officialUrl: `${ONS}/employmentandlabourmarket/peopleinwork/employmentandemployeetypes`,
    docsUrl: `${ONS}/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/bulletins/uklabourmarket/latest`,
    releaseName: "Labour Market",
  },
  {
    id: "uk-awe-total-yoy",
    region: "UK",
    category: "jobs",
    subcategory: "wages",
    name: "UK Average Weekly Earnings (Total Pay) YoY",
    shortName: "AWE Total",
    description: "Total pay 3-month average YoY including bonuses (ONS KAC3).",
    source: "ons",
    seriesId: "KAC3",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${ONS}/employmentandlabourmarket/peopleinwork/earningsandworkinghours`,
    docsUrl: `${ONS}/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/bulletins/averageweeklyearningsingreatbritain/latest`,
    releaseName: "Average Weekly Earnings",
  },
  {
    id: "uk-vacancies",
    region: "UK",
    category: "jobs",
    subcategory: "vacancies",
    name: "UK Job Vacancies",
    shortName: "UK Vacancies",
    description: "Estimated number of job vacancies (ONS).",
    source: "ons",
    seriesId: "AP2Y",
    transform: "level",
    frequency: "monthly",
    unit: "thousands",
    importance: "high",
    officialUrl: `${ONS}/employmentandlabourmarket/peopleinwork/employmentandemployeetypes`,
    docsUrl: `${ONS}/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/bulletins/uklabourmarket/latest`,
    releaseName: "Labour Market",
  },

  // ─── EURO AREA INFLATION ────────────────────────────────────
  {
    id: "ea-hicp-yoy",
    region: "EA",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "Euro Area HICP YoY",
    shortName: "HICP YoY",
    description: "Harmonised Index of Consumer Prices annual rate (Eurostat prc_hicp_minr).",
    source: "eurostat",
    seriesId: "prc_hicp_minr",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${EUROSTAT}/web/hicp`,
    docsUrl: `${EUROSTAT}/databrowser/view/prc_hicp_minr/default/table`,
    releaseName: "Euro Area HICP",
  },
  {
    id: "ea-core-hicp-yoy",
    region: "EA",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "Euro Area Core HICP YoY",
    shortName: "Core HICP",
    description: "HICP excluding energy, food, alcohol and tobacco (Eurostat).",
    source: "eurostat",
    seriesId: "prc_hicp_minr_core",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${EUROSTAT}/web/hicp`,
    docsUrl: `${EUROSTAT}/databrowser/view/prc_hicp_minr/default/table`,
    releaseName: "Euro Area HICP",
  },
  {
    id: "ea-hicp-mom",
    region: "EA",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "Euro Area HICP MoM",
    shortName: "HICP MoM",
    description: "Euro area HICP monthly rate (Eurostat RCH_M).",
    source: "eurostat",
    seriesId: "prc_hicp_mmor",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${EUROSTAT}/web/hicp`,
    docsUrl: `${EUROSTAT}/databrowser/view/prc_hicp_minr/default/table`,
    releaseName: "Euro Area HICP",
  },
  {
    id: "ea-core-hicp-mom",
    region: "EA",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "Euro Area Core HICP MoM",
    shortName: "Core HICP MoM",
    description: "Euro area core HICP monthly rate (ex energy/food).",
    source: "eurostat",
    seriesId: "prc_hicp_mmor_core",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${EUROSTAT}/web/hicp`,
    docsUrl: `${EUROSTAT}/databrowser/view/prc_hicp_minr/default/table`,
    releaseName: "Euro Area HICP",
  },
  {
    id: "ea-services-hicp-yoy",
    region: "EA",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "Euro Area Services HICP YoY",
    shortName: "EA Svc HICP",
    description: "Euro area HICP services annual rate (coicop18 SERV).",
    source: "eurostat",
    seriesId: "prc_hicp_minr_serv",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${EUROSTAT}/web/hicp`,
    docsUrl: `${EUROSTAT}/databrowser/view/prc_hicp_minr/default/table`,
    releaseName: "Euro Area HICP",
  },
  {
    id: "ea-services-hicp-mom",
    region: "EA",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "Euro Area Services HICP MoM",
    shortName: "EA Svc MoM",
    description: "Euro area HICP services monthly rate.",
    source: "eurostat",
    seriesId: "prc_hicp_mmor_serv",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${EUROSTAT}/web/hicp`,
    docsUrl: `${EUROSTAT}/databrowser/view/prc_hicp_minr/default/table`,
    releaseName: "Euro Area HICP",
  },
  {
    id: "ea-goods-hicp-yoy",
    region: "EA",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "Euro Area Goods HICP YoY",
    shortName: "EA Goods HICP",
    description: "Euro area HICP goods annual rate (coicop18 GD).",
    source: "eurostat",
    seriesId: "prc_hicp_minr_goods",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${EUROSTAT}/web/hicp`,
    docsUrl: `${EUROSTAT}/databrowser/view/prc_hicp_minr/default/table`,
    releaseName: "Euro Area HICP",
  },
  {
    id: "ea-food-hicp-yoy",
    region: "EA",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "Euro Area Food HICP YoY",
    shortName: "EA Food HICP",
    description: "Euro area HICP food annual rate (coicop18 FOOD).",
    source: "eurostat",
    seriesId: "prc_hicp_minr_food",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${EUROSTAT}/web/hicp`,
    docsUrl: `${EUROSTAT}/databrowser/view/prc_hicp_minr/default/table`,
    releaseName: "Euro Area HICP",
  },
  {
    id: "ea-energy-hicp-yoy",
    region: "EA",
    category: "inflation",
    subcategory: "consumer_prices",
    name: "Euro Area Energy HICP YoY",
    shortName: "EA Energy HICP",
    description: "Euro area HICP energy annual rate (coicop18 NRG).",
    source: "eurostat",
    seriesId: "prc_hicp_minr_nrg",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${EUROSTAT}/web/hicp`,
    docsUrl: `${EUROSTAT}/databrowser/view/prc_hicp_minr/default/table`,
    releaseName: "Euro Area HICP",
  },
  {
    id: "de-cpi-yoy",
    region: "EA",
    category: "inflation",
    subcategory: "national_cpi",
    name: "Germany HICP YoY",
    shortName: "DE CPI",
    description: "German HICP annual rate (Eurostat prc_hicp_minr).",
    source: "eurostat",
    seriesId: "prc_hicp_minr_DE",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: "https://www.destatis.de",
    docsUrl: "https://www.destatis.de/EN/Themes/Economy/Prices/Consumer-Price-Index/_node.html",
    releaseName: "German CPI",
  },
  {
    id: "fr-cpi-yoy",
    region: "EA",
    category: "inflation",
    subcategory: "national_cpi",
    name: "France HICP YoY",
    shortName: "FR CPI",
    description: "French HICP annual rate (Eurostat prc_hicp_minr).",
    source: "eurostat",
    seriesId: "prc_hicp_minr_FR",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: "https://www.insee.fr",
    docsUrl: "https://www.insee.fr/en/statistiques/serie/001759971",
    releaseName: "French CPI",
  },
  {
    id: "it-cpi-yoy",
    region: "EA",
    category: "inflation",
    subcategory: "national_cpi",
    name: "Italy HICP YoY",
    shortName: "IT CPI",
    description: "Italian HICP annual rate (Eurostat prc_hicp_minr).",
    source: "eurostat",
    seriesId: "prc_hicp_minr_IT",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "medium",
    officialUrl: "https://www.istat.it",
    docsUrl: "https://www.istat.it/en/prices",
    releaseName: "Italian CPI",
  },
  {
    id: "es-cpi-yoy",
    region: "EA",
    category: "inflation",
    subcategory: "national_cpi",
    name: "Spain HICP YoY",
    shortName: "ES CPI",
    description: "Spanish HICP annual rate (Eurostat prc_hicp_minr).",
    source: "eurostat",
    seriesId: "prc_hicp_minr_ES",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "medium",
    officialUrl: "https://www.ine.es",
    docsUrl: "https://www.ine.es/en/",
    releaseName: "Spanish CPI",
  },
  {
    id: "ea-ppi-yoy",
    region: "EA",
    category: "inflation",
    subcategory: "producer_prices",
    name: "Euro Area PPI YoY",
    shortName: "EA PPI",
    description: "Euro area producer prices in industry (Eurostat sts_inpp_m, YoY from index).",
    source: "eurostat",
    seriesId: "sts_inpp_m",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${EUROSTAT}/web/short-term-business-statistics`,
    docsUrl: `${EUROSTAT}/databrowser/view/sts_inpp_m/default/table`,
    releaseName: "Industrial Producer Prices",
  },
  {
    id: "ea-unemployed-persons",
    region: "EA",
    category: "jobs",
    subcategory: "unemployment",
    name: "Euro Area Unemployed Persons",
    shortName: "EA Unemployed",
    description: "Unemployed persons, euro area (Eurostat ei_lmhu_m, thousands).",
    source: "eurostat",
    seriesId: "ei_lmhu_m",
    transform: "level",
    frequency: "monthly",
    unit: "thousands",
    importance: "high",
    officialUrl: `${EUROSTAT}/web/labour-market`,
    docsUrl: `${EUROSTAT}/databrowser/view/ei_lmhu_m/default/table`,
    releaseName: "Euro Area Unemployment",
  },

  // ─── EURO AREA GROWTH ───────────────────────────────────────
  {
    id: "ea-gdp-yoy",
    region: "EA",
    category: "growth",
    subcategory: "gdp",
    name: "Euro Area Real GDP YoY",
    shortName: "EA GDP YoY",
    description: "Euro area real GDP year-over-year.",
    source: "fred",
    seriesId: "CLVMNACSCAB1GQEA19",
    transform: "pct_change_yoy",
    frequency: "quarterly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${EUROSTAT}/web/national-accounts`,
    docsUrl: `${EUROSTAT}/web/national-accounts/publications`,
    releaseName: "Euro Area GDP",
  },
  {
    id: "ea-gdp-qoq",
    region: "EA",
    category: "growth",
    subcategory: "gdp",
    name: "Euro Area Real GDP QoQ",
    shortName: "EA GDP QoQ",
    description: "Euro area real GDP quarter-over-quarter.",
    source: "fred",
    seriesId: "CLVMNACSCAB1GQEA19",
    transform: "pct_change",
    frequency: "quarterly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${EUROSTAT}/web/national-accounts`,
    docsUrl: `${EUROSTAT}/web/national-accounts/publications`,
    releaseName: "Euro Area GDP",
  },
  {
    id: "ea-industrial-production",
    region: "EA",
    category: "growth",
    subcategory: "production",
    name: "Euro Area Industrial Production YoY",
    shortName: "EA IP",
    description: "Industrial production excluding construction (Eurostat sts_inpr_m I21, YoY).",
    source: "eurostat",
    seriesId: "sts_inpr_m",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${EUROSTAT}/web/short-term-business-statistics`,
    docsUrl: `${EUROSTAT}/databrowser/view/sts_inpr_m/default/table`,
    releaseName: "Industrial Production",
  },
  {
    id: "ea-retail-sales",
    region: "EA",
    category: "growth",
    subcategory: "demand",
    name: "Euro Area Retail Trade YoY",
    shortName: "EA Retail",
    description: "Retail trade volume annual growth (Eurostat ei_isrr_m).",
    source: "eurostat",
    seriesId: "ei_isrr_m",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${EUROSTAT}/web/short-term-business-statistics`,
    docsUrl: `${EUROSTAT}/databrowser/view/ei_isrr_m/default/table`,
    releaseName: "Retail Trade",
  },
  {
    id: "ea-esi",
    region: "EA",
    category: "growth",
    subcategory: "sentiment",
    name: "Euro Area Economic Sentiment",
    shortName: "EA ESI",
    description: "EC Economic Sentiment Indicator (Eurostat ei_bssi_m_r2).",
    source: "eurostat",
    seriesId: "ei_bssi_esi",
    transform: "level",
    frequency: "monthly",
    unit: "index",
    importance: "high",
    officialUrl: "https://economy-finance.ec.europa.eu/economic-forecast-and-surveys/business-and-consumer-surveys_en",
    docsUrl: `${EUROSTAT}/databrowser/view/ei_bssi_m_r2/default/table`,
    releaseName: "Business and Consumer Surveys",
  },
  {
    id: "ea-business-confidence",
    region: "EA",
    category: "growth",
    subcategory: "sentiment",
    name: "Euro Area Industrial Confidence",
    shortName: "EA Biz Conf",
    description: "EC industrial confidence indicator (Eurostat).",
    source: "eurostat",
    seriesId: "ei_bssi_ici",
    transform: "level",
    frequency: "monthly",
    unit: "index",
    importance: "high",
    officialUrl: "https://economy-finance.ec.europa.eu/economic-forecast-and-surveys/business-and-consumer-surveys_en",
    docsUrl: `${EUROSTAT}/databrowser/view/ei_bssi_m_r2/default/table`,
    releaseName: "Business and Consumer Surveys",
  },

  // ─── EURO AREA JOBS ─────────────────────────────────────────
  {
    id: "ea-unemployment",
    region: "EA",
    category: "jobs",
    subcategory: "unemployment",
    name: "Euro Area Unemployment Rate",
    shortName: "EA U-Rate",
    description: "Harmonised unemployment rate (Eurostat EA21).",
    source: "eurostat",
    seriesId: "une_rt_m",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "critical",
    officialUrl: `${EUROSTAT}/web/labour-market/statistics-illustrated`,
    docsUrl: `${EUROSTAT}/databrowser/view/une_rt_m/default/table`,
    releaseName: "Euro Area Unemployment",
  },
  {
    id: "de-unemployment",
    region: "EA",
    category: "jobs",
    subcategory: "national_jobs",
    name: "Germany Unemployment Rate",
    shortName: "DE U-Rate",
    description: "German harmonised unemployment rate.",
    source: "fred",
    seriesId: "LRHUTTTTDEM156S",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: "https://www.destatis.de",
    docsUrl: "https://www.destatis.de/EN/Themes/Labour/Labour-Market/_node.html",
    releaseName: "German Labour Market",
  },
  {
    id: "ea-employment-yoy",
    region: "EA",
    category: "jobs",
    subcategory: "employment",
    name: "Euro Area Unemployed Persons YoY",
    shortName: "EA Unemp YoY",
    description: "Year-over-year change in unemployed persons (Eurostat ei_lmhu_m).",
    source: "eurostat",
    seriesId: "ei_lmhu_m",
    transform: "pct_change_yoy",
    frequency: "monthly",
    unit: "percent",
    importance: "high",
    officialUrl: `${EUROSTAT}/web/labour-market`,
    docsUrl: `${EUROSTAT}/databrowser/view/ei_lmhu_m/default/table`,
    releaseName: "Euro Area Unemployment",
  },
  {
    id: "ea-youth-unemployment",
    region: "EA",
    category: "jobs",
    subcategory: "unemployment",
    name: "Euro Area Youth Unemployment Rate",
    shortName: "EA Youth U",
    description: "Unemployment rate for persons under 25 (Eurostat EA21).",
    source: "eurostat",
    seriesId: "une_rt_m_youth",
    transform: "level",
    frequency: "monthly",
    unit: "percent",
    importance: "medium",
    officialUrl: `${EUROSTAT}/web/labour-market`,
    docsUrl: `${EUROSTAT}/databrowser/view/une_rt_m/default/table`,
    releaseName: "Euro Area Unemployment",
  },
];

export const X_HANDLES = [
  { id: "adp", handle: "@ADP_Employment", displayName: "ADP Employment Report", region: "US", role: "official", notes: "ADP National Employment Report (private payrolls)" },
  { id: "bls", handle: "@BLS_gov", displayName: "U.S. Bureau of Labor Statistics", region: "US", role: "official", notes: "CPI, PPI, NFP, JOLTS, ECI releases" },
  { id: "bea", handle: "@BEA_News", displayName: "Bureau of Economic Analysis", region: "US", role: "official", notes: "GDP, PCE, personal income" },
  { id: "census", handle: "@uscensusbureau", displayName: "U.S. Census Bureau", region: "US", role: "official", notes: "Retail sales, durables, housing" },
  { id: "fed", handle: "@federalreserve", displayName: "Federal Reserve", region: "US", role: "official", notes: "IP, policy, beige book" },
  { id: "atlantafed", handle: "@AtlantaFed", displayName: "Atlanta Fed", region: "US", role: "official", notes: "GDPNow, Wage Growth Tracker, sticky CPI" },
  { id: "nyfed", handle: "@NewYorkFed", displayName: "New York Fed", region: "US", role: "official", notes: "SCE inflation expectations" },
  { id: "chicagofed", handle: "@ChicagoFed", displayName: "Chicago Fed", region: "US", role: "official", notes: "CFNAI" },
  { id: "clevelandfed", handle: "@ClevelandFed", displayName: "Cleveland Fed", region: "US", role: "official", notes: "Median / trimmed CPI" },
  { id: "stlouisfed", handle: "@stlouisfed", displayName: "St. Louis Fed / FRED", region: "US", role: "official", notes: "FRED data platform" },
  { id: "ism", handle: "@ISMReport", displayName: "ISM", region: "US", role: "official", notes: "Manufacturing & Services PMI" },
  { id: "spglobalpmi", handle: "@S_PGlobalPMI", displayName: "S&P Global PMI", region: "US", role: "official", notes: "Flash & final PMI US/UK/EZ" },
  { id: "ons", handle: "@ONS", displayName: "Office for National Statistics", region: "UK", role: "official", notes: "UK CPI, GDP, labour market, AWE" },
  { id: "boe", handle: "@bankofengland", displayName: "Bank of England", region: "UK", role: "official", notes: "Policy, Decision Maker Panel, inflation attitudes" },
  { id: "ecb", handle: "@ecb", displayName: "European Central Bank", region: "EA", role: "official", notes: "SPF, CES, wage tracker, policy" },
  { id: "eurostat", handle: "@EU_Eurostat", displayName: "Eurostat", region: "EA", role: "official", notes: "HICP, GDP, unemployment, IP" },
  { id: "destatis", handle: "@destatis", displayName: "Destatis", region: "EA", role: "official", notes: "German CPI flash & final" },
  { id: "insee", handle: "@InseeFr", displayName: "INSEE", region: "EA", role: "official", notes: "French CPI & GDP" },
  { id: "nicktimiraos", handle: "@NickTimiraos", displayName: "Nick Timiraos", region: "US", role: "analyst", notes: "WSJ Fed reporter — release framing" },
  { id: "lisaabramowicz", handle: "@LisaAbramowicz", displayName: "Lisa Abramowicz", region: "US", role: "analyst", notes: "Bloomberg — data & markets" },
  { id: "thestalwart", handle: "@TheStalwart", displayName: "Joe Weisenthal", region: "US", role: "analyst", notes: "Odd Lots — what markets watch" },
  { id: "edwardlawrence", handle: "@EdwardLawrence", displayName: "Edward Lawrence", region: "UK", role: "analyst", notes: "Sky News — UK data flow" },
  { id: "johnauthers", handle: "@JohnAuthers", displayName: "John Authers", region: "US", role: "analyst", notes: "Points of Return — macro tape" },
];

export function getMetric(id: string): MetricDef | undefined {
  return METRICS.find((m) => m.id === id);
}

export function metricsByRegion(region: Region): MetricDef[] {
  return METRICS.filter((m) => m.region === region);
}

export function uniqueFredSeries(): string[] {
  return [...new Set(METRICS.filter((m) => m.source === "fred").map((m) => m.seriesId))];
}
